export const ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const ALL_MOVIES = "GET_ALL_MOVIES";
export const MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const ALL_MOVIES_ERROR = "GET_ALL_MOVIES_ERROR";
